; File containing all the test cases
(equal? (compare-expr 12 12) 12) 
(equal? (compare-expr 12 20) '(if TCP 12 20)) 
(equal? (compare-expr #t #t) #t) 
(equal? (compare-expr #f #f) #f) 
(equal? (compare-expr #t #f) 'TCP )
(equal? (compare-expr #f #t) '(not TCP)) 
(equal? (compare-expr 'a '(cons a b)) '(if TCP a (cons a b)))
(equal? (compare-expr '(cons a b) '(cons a b)) '(cons a b)   )     
(equal? (compare-expr '(cons a b) '(cons a c)) '(cons a (if TCP b c)) )
(equal? (compare-expr '(cons (cons a b) (cons b c))
              '(cons (cons a c) (cons a c))) 
          '(cons (cons a (if TCP b c)) (cons (if TCP b a) c)))
(equal? (compare-expr '(cons a b) '(list a b)) '((if TCP cons list) a b))  
(equal? (compare-expr '(list) '(list a)) '(if TCP (list) (list a))) 
(equal? (compare-expr ''(a b) ''(a c)) '(if TCP '(a b) '(a c)))
(equal? (compare-expr '(quote (a b)) '(quote (a c))) '(if TCP '(a b) '(a c))) 
(equal? (compare-expr '(quoth (a b)) '(quoth (a c))) '(quoth (a (if TCP b c)))) 
(equal? (compare-expr '(if x y z) '(if x z z)) '(if x (if TCP y z) z)) 
(equal? (compare-expr '(if x y z) '(g x y z)) '(if TCP (if x y z) (g x y z))) 
;TODO:  Not working
(equal? (compare-expr '(let ((a 1)) (f a)) '(let ((a 2)) (g a))) '(let ((a (if TCP 1 2))) ((if TCP f g) a)))
(equal? (compare-expr '(+ #f (let ((a 1) (b 2)) (f a b)))
              '(+ #t (let ((a 1) (c 2)) (f a c))))
          '(+
        (not TCP)
        (if TCP
            (let ((a 1) (b 2)) (f a b))
            (let ((a 1) (c 2)) (f a c)))))
(equal? (compare-expr '((lambda (a) (f a)) 1) '((lambda (a) (g a)) 2)) '((lambda (a) ((if TCP f g) a)) (if TCP 1 2)))

(equal? (compare-expr '((lambda (a b) (f a b)) 1 2)
              '((lambda (a b) (f b a)) 1 2))
          '((lambda (a b) (f (if TCP a b) (if TCP b a))) 1 2))

(equal? (compare-expr '((lambda (a b) (f a b)) 1 2)
              '((lambda (a c) (f c a)) 1 2)) 
          '((if TCP (lambda (a b) (f a b))
		(lambda (a c) (f c a))) 1 2))
